name: Maven Clean Install Action
description: A composite action to ensure that code builds correctly

# Inputs
inputs:
  branch_name: 
    description: "Current Branch"
    required: true
    default: "main"
  sonarcloud_token:
       description: "Token For Sonarcloud"
       required: false
  sonarcloud_host_url:     
       description: "Sonarcloud Host URL"
       required: false
  sonarcloud_organization:
       description: "Organization Name on Sonarcloud "
       required: false
  sonarcloud_sources:
       description: "source folder"
       required: false   
  sonarcloud_projectKey:
       description: "Sonar project key"
       required: false
  sonarcloud_coverage_jacoco_xmlReportPaths:
       description: "Jacoco reports path"
       required: false
  sonarcloud_java_binaries:
       description: "Java binaries folder"
       required: false         
  sonarcloud_tests:
       description: "Java test folder"
       required: false   
       
runs:
  using: "composite" 
  steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v4

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Maven Build
      if: github.event.repository.name != 'reasoner-test-data' && (inputs.branch_name == 'main' || inputs.branch_name == 'master')
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dmaven.build.cache.enabled=false \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -PcodeQuality

    - name: Maven Build -- Feature Branch
      if: github.event.repository.name == 'reasoner-test-data' || (inputs.branch_name != 'main' && inputs.branch_name != 'master')
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Denforcer.skip=true \
            -PcodeQuality
  
