name: Maven Clean Install Action
description: A composite action to ensure that code builds correctly

# Inputs
inputs:
  branch_name: 
    description: "Current Branch"
    required: true
  skip_setup:
    description: "Skip Setup"
    required: false
    default: false
  working_directory:
    description: "Working Directory"
    required: false
    default: "."
  java_distribution:
    description: "Java Distribution"
    required: false
    default: "zulu"
  java_version:
    description: "Java Version"
    required: false 
    default: "24.01"
  mvn_additional_args:
    description: "Additional Maven CLI args (no new lines)"
    required: false
    default: ""
    
runs:
  using: "composite" 
  steps:
    - name: Checkout Repository
      if: ${{ inputs.skip_setup != 'true' && inputs.skip_setup != 'yes' }}
      uses: actions/checkout@v4

    - name: Setup Java
      if: ${{ inputs.skip_setup != 'true' && inputs.skip_setup != 'yes' }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{inputs.java_distribution}}
        java-version: ${{inputs.java_version}}

    - name: Cache Maven packages
      if: ${{ inputs.skip_setup != 'true' && inputs.skip_setup != 'yes' }}
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Maven Build
      if: github.event.repository.name != 'reasoner-test-data' && inputs.branch_name == github.event.repository.default_branch
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dmaven.build.cache.enabled=false \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -PcodeQuality \
            -PgenerateData \
            ${{ inputs.mvn_additional_args }}
      working-directory: ${{inputs.working_directory}}

    - name: Maven Build -- Feature Branch
      if: github.event.repository.name == 'reasoner-test-data' || inputs.branch_name != github.event.repository.default_branch
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Denforcer.skip=true \
            -PcodeQuality \
            -PgenerateData \
            ${{ inputs.mvn_additional_args }}
      working-directory: ${{inputs.working_directory}}
  
