name: Maven Clean Install Action
description: A composite action to ensure that code builds correctly

# Inputs
inputs:
  branch_name: 
    description: "Current Branch"
    required: true
  perform_setup:
    description: "Perform Setup"
    required: false
    type: boolean
    default: true
  java_version:
    description: "Java Version"
    required: false 
    default: "23"
    
runs:
  using: "composite" 
  steps:
    - name: Check Input
      shell: bash
      run: |
        echo "Do setup: ${{inputs.perform_setup}}"

    - name: Check Input True
      if: inputs.perform_setup
      shell: bash
      run: |
        echo "Condition was TRUE"

    - name: Check Input False
      if: ${{ ! inputs.perform_setup }}
      shell: bash
      run: |
        echo "Condition was FALSE"

    - name: Checkout Repository
      if: inputs.perform_setup
      uses: actions/checkout@v4

    - name: Setup Java
      if: inputs.perform_setup
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{inputs.java_version}}

    - name: Cache Maven packages
      if: inputs.perform_setup
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Maven Build
      if: github.event.repository.name != 'reasoner-test-data' && inputs.branch_name == github.event.repository.default_branch
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dmaven.build.cache.enabled=false \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -PcodeQuality

    - name: Maven Build -- Feature Branch
      if: github.event.repository.name == 'reasoner-test-data' || inputs.branch_name != github.event.repository.default_branch
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Denforcer.skip=true \
            -PcodeQuality
  
