name: Maven Clean Install Action
description: A composite action to ensure that code builds correctly

# Inputs
inputs:
  branch_name: 
    description: "Current Branch"
    required: true
    default: "main"
 
       
runs:
  using: "composite" 
  steps:
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-


    - name: Verification Step
       id: verification_step
       shell: bash
       run: |
            echo "Is Default Branch: ${{inputs.branch_name}} || $IS_DEFAULT_BRANCH"
            echo "Is Reasoner Test Data Repo: ${{github.event.repository.name}} || $IS_REASONER_TEST_DATA_REPO"
            echo "Is Pull Request Event: ${{github.event_name}} || $IS_PULL_REQUEST_EVENT"
            
            if [ $IS_PULL_REQUEST_EVENT == 'true' ]; then
             echo "ENFORCER_FLAG=true">> $GITHUB_OUTPUT
            elif [ $IS_DEFAULT_BRANCH == 'true' ]; then
             echo "ENFORCER_FLAG=true">> $GITHUB_OUTPUT
            elif [ $IS_DEFAULT_BRANCH == 'false' ]; then
             echo "ENFORCER_FLAG=false">> $GITHUB_OUTPUT
            else
             echo "ERROR!"
             exit 1
            fi
       env:
         IS_DEFAULT_BRANCH: ${{ inputs.branch_name == 'main' || inputs.branch_name == 'master' }}
         IS_REASONER_TEST_DATA_REPO: ${{ github.event.repository.name == 'reasoner-test-data' }}
         IS_PULL_REQUEST_EVENT: ${{ github.event_name == 'pull_request' }}

    - name: Maven Build
      # if: github.event.repository.name != 'reasoner-test-data' && (inputs.branch_name == 'main' || inputs.branch_name == 'master')
      shell: bash
      run: |
          ./mvnw clean install -U \
            --batch-mode \
            -e \
            -Dmaven.build.cache.enabled=false \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Denforcer.skip=${{steps.verification_step.outputs.ENFORCER_FLAG}} \
            -PcodeQuality

    # - name: Maven Build -- Feature Branch
    #   if: github.event.repository.name == 'reasoner-test-data' || (inputs.branch_name != 'main' && inputs.branch_name != 'master')
    #   shell: bash
    #   run: |
    #       ./mvnw clean install -U \
    #         --batch-mode \
    #         -e \
    #         -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
    #         -Denforcer.skip=true \
    #         -PcodeQuality
  
